server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
      - id: cartModule
        uri: http://localhost:8082/
        predicates:
        - Path=/cart/**
      - id: sachModule
        uri: http://localhost:8083/
        predicates:
        - Path=/sach/**